name = "admin2121"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern="eko-cs.my.id"
custom_domain=true

[vars]
# PROXYIP = "91.192.81.154:2053"
UUID = "0196e782-af40-7d85-8027-b8f56f116070"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
